# Generated by Django 5.0.3 on 2025-09-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_original', models.CharField(max_length=200)),
                ('word_translation', models.CharField(max_length=200)),
                ('transcription', models.CharField(blank=True, max_length=200)),
                ('example_sentence', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('audio_original', models.FileField(blank=True, null=True, upload_to='audio/original/')),
                ('audio_translation', models.FileField(blank=True, null=True, upload_to='audio/translation/')),
                ('audio_example', models.FileField(blank=True, null=True, upload_to='audio/example/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('ru', 'Russian')], default='en', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='deck_covers/')),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cards_studied', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('session_type', models.CharField(choices=[('new', 'Новые'), ('review', 'Повторение')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetition_count', models.IntegerField(default=0)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('learning', 'Изучается'), ('review', 'На повторении'), ('mastered', 'Выучено')], default='new', max_length=10)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['next_review_date'],
            },
        ),
    ]
