# Generated by Django 5.0.3 on 2025-09-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('message_text', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('command', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_username',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='daily_reminders_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_chat_id',
            new_name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='linked_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
